version: '2.4'
services:
  app:
    container_name: "application-server"
    image: <your app image> 
    restart: always
    volumes:
      - ..:/workspace:cached
    ports:
      - '<port>:<port>'
    networks:
      - app-network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
networks:
  app-network:
    external: true